using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NoteTakingApp.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class SeedCountriesAndLanguages : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder builder)
        {
            #region  Seek Countries
                        builder.Sql(@"
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Afghanistan',N'أفغانستان','AF','AFG',93);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Åland Islands',N'جزر أولاند','AX','ALA',358);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Albania',N'ألبانيا','AL','ALB',355);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Algeria',N'الجزائر','DZ','DZA',213);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('American Samoa',N'ساموا الأمريكية','AS','ASM',684);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Andorra',N'أندورا','AD','AND',376);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Angola',N'أنغولا','AO','AGO',244);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Anguilla',N'أنغويلا','AI','AIA',264);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Antarctica',N'القارة القطبية الجنوبية','AQ','ATA',672);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Antigua and Barbuda',N'أنتيغوا وبربودا','AG','ATG',268);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Argentina',N'الأرجنتين','AR','ARG',54);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Armenia',N'أرمينيا','AM','ARM',374);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Aruba',N'أروبا','AW','ABW',297);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Australia',N'أستراليا','AU','AUS',61);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Austria',N'النمسا','AT','AUT',43);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Azerbaijan',N'أذربيجان','AZ','AZE',994);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Bahamas',N'باهاماس','BS','BHS',1);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Bahrain',N'البحرين','BH','BHR',973);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Bangladesh',N'بنغلاديش','BD','BGD',880);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Barbados',N'بربادوس','BB','BRB',246);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Belarus',N'بيلاروسيا','BY','BLR',375);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Belgium',N'بلجيكا','BE','BEL',32);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Belize',N'بليز','BZ','BLZ',501);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Benin',N'بنين','BJ','BEN',229);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Bermuda',N'برمودا','BM','BMU',1);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Bhutan',N'بوتان','BT','BTN',975);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Bolivia',N'بوليفيا','BO','BOL',591);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Bosnia and Herzegovina',N'البوسنة والهرسك','BA','BIH',387);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Botswana',N'بوتسوانا','BW','BWA',267);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Bouvet Island',N'جزيرة بوفيه','BV','BVT',47);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Brazil',N'البرازيل','BR','BRA',55);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('British Indian Ocean Territory',N'إقليم المحيط الهندي البريطاني','IO','IOT',246);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('British Virgin Islands',N'جزر العذراء البريطانية','VG','VGB',1);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Brunei',N'بروناي','BN','BRN',673);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Bulgaria',N'بلغاريا','BG','BGR',359);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Burkina Faso',N'بوركينا فاسو','BF','BFA',226);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Burundi',N'بوروندي','BI','BDI',257);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Cabo Verde',N'كابو فيردي','CV','CPV',238);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Cambodia',N'كمبوديا','KH','KHM',855);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Cameroon',N'الكاميرون','CM','CMR',237);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Canada',N'كندا','CA','CAN',1);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Caribbean Netherlands',N'الجزر الكاريبية الهولندية','BQ','BES',599);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Cayman Islands',N'جزر كايمان','KY','CYM',1345);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Central African Republic',N'جمهورية أفريقيا الوسطى','CF','CAF',236);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Chad',N'تشاد','TD','TCD',235);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Chile',N'تشيلي','CL','CHL',56);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('China',N'الصين','CN','CHN',86);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Christmas Island',N'جزيرة الكريسماس','CX','CXR',61);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Cocos (Keeling) Islands',N'جزر كوكوس','CC','CCK',61);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Colombia',N'كولومبيا','CO','COL',57);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Comoros',N'جزر القمر','KM','COM',269);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Congo Republic',N'جمهورية الكونغو','CG','COG',242);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Cook Islands',N'جزر كوك','CK','COK',682);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Costa Rica',N'كوستاريكا','CR','CRI',506);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Croatia',N'كرواتيا','HR','HRV',385);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Cuba',N'كوبا','CU','CUB',53);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Curaçao',N'كوراساو','CW','CUW',599);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Cyprus',N'قبرص','CY','CYP',357);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Czechia',N'التشيك','CZ','CZE',420);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Denmark',N'الدنمارك','DK','DNK',45);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Djibouti',N'جيبوتي','DJ','DJI',253);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Dominica',N'دومينيكا','DM','DMA',767);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Dominican Republic',N'جمهورية الدومينيكان','DO','DOM',1);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('DR Congo',N'جمهورية الكونغو الديمقراطية','CD','COD',243);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Ecuador',N'الاكوادور','EC','ECU',593);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Egypt',N'مصر','EG','EGY',20);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('El Salvador',N'السلفادور','SV','SLV',503);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Equatorial Guinea',N'غينيا الاستوائية','GQ','GNQ',240);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Eritrea',N'إريتريا','ER','ERI',291);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Estonia',N'إستونيا','EE','EST',372);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Eswatini',N'إسواتيني','SZ','SWZ',268);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Ethiopia',N'إثيوبيا','ET','ETH',251);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Falkland Islands',N'جزر فوكلاند','FK','FLK',500);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Faroe Islands',N'جزر فارو','FO','FRO',298);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Fiji',N'فيجي','FJ','FJI',679);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Finland',N'فنلندا','FI','FIN',358);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('France',N'فرنسا','FR','FRA',33);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('French Guiana',N'غويانا الفرنسية','GF','GUF',594);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('French Polynesia',N'بولينزيا الفرنسية','PF','PYF',689);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('French Southern Territories',N'أراض فرنسية جنوبية','TF','ATF',262);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Gabon',N'الجابون','GA','GAB',241);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Gambia',N'غامبيا','GM','GMB',220);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Georgia',N'‫جورجيا','GE','GEO',995);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Germany',N'ألمانيا','DE','DEU',49);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Ghana',N'غانا','GH','GHA',233);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Gibraltar',N'جبل طارق','GI','GIB',350);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Greece',N'اليونان','GR','GRC',30);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Greenland',N'جرينلاند','GL','GRL',299);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Grenada',N'غرينادا','GD','GRD',473);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Guadeloupe',N'غوادلوب','GP','GLP',590);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Guam',N'غوام','GU','GUM',1);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Guatemala',N'غواتيمالا','GT','GTM',502);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Guernsey',N'غيرنزي','GG','GGY',44);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Guinea',N'غينيا','GN','GIN',224);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Guinea_Bissau',N'غينيا بيساو','GW','GNB',245);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Guyana',N'غيانا','GY','GUY',592);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Haiti',N'هايتي','HT','HTI',509);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Heard Island and McDonald Islands',N'جزيرة هيرد وجزر ماكدونالد','HM','HMD',672);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Honduras',N'هندوراس','HN','HND',504);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Hong Kong',N'هونج كونج','HK','HKG',852);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Hungary',N'هنجاريا','HU','HUN',36);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Iceland',N'آيسلندا','IS','ISL',354);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('India',N'الهند','IN','IND',91);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Indonesia',N'أندونيسيا','ID','IDN',62);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Iran',N'إيران','IR','IRN',98);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Iraq',N'العراق','IQ','IRQ',964);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Ireland',N'أيرلندا','IE','IRL',353);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Isle of Man',N'جزيرة مان','IM','IMN',44);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Italy',N'إيطاليا','IT','ITA',390);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Ivory Coast',N'ساحل العاج','CI','CIV',225);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Jamaica',N'جامايكا','JM','JAM',1876);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Japan',N'اليابان','JP','JPN',81);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Jersey',N'جيرسي','JE','JEY',44);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Jordan',N'الأردن','JO','JOR',962);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Kazakhstan',N'كازاخستان','KZ','KAZ',7);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Kenya',N'كينيا','KE','KEN',254);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Kiribati',N'كيريباتي','KI','KIR',686);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Kosovo',N'كوسوفو','XK','XKX',383);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Kuwait',N'الكويت','KW','KWT',965);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Kyrgyzstan',N'قيرغيزستان','KG','KGZ',996);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Laos',N'لاوس','LA','LAO',856);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Latvia',N'لاتفيا','LV','LVA',371);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Lebanon',N'لبنان','LB','LBN',961);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Lesotho',N'ليسوتو','LS','LSO',266);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Liberia',N'ليبيريا','LR','LBR',231);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Libya',N'ليبيا','LY','LBY',218);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Liechtenstein',N'ليختنشتاين','LI','LIE',423);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Lithuania',N'ليتوانيا','LT','LTU',370);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Luxembourg',N'لوكسمبورغ','LU','LUX',352);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Macao',N'ماكاو','MO','MAC',853);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Madagascar',N'مدغشقر','MG','MDG',261);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Malawi',N'مالاوي','MW','MWI',265);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Malaysia',N'ماليزيا','MY','MYS',60);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Maldives',N'المالديف','MV','MDV',960);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Mali',N'مالي','ML','MLI',223);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Malta',N'مالطا','MT','MLT',356);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Marshall Islands',N'جزر مارشال','MH','MHL',692);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Martinique',N'مارتينيك','MQ','MTQ',33);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Mauritania',N'موريتانيا','MR','MRT',222);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Mauritius',N'موريشيوس','MU','MUS',230);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Mayotte',N'مايوت','YT','MYT',262);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Mexico',N'المكسيك','MX','MEX',52);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Micronesia',N'ولايات ميكرونيسيا المتحدة','FM','FSM',691);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Moldova',N'مولدوفا','MD','MDA',373);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Monaco',N'موناكو','MC','MCO',377);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Mongolia',N'منغوليا','MN','MNG',976);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Montenegro',N'مونتينيغرو','ME','MNE',382);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Montserrat',N'مونتسرات','MS','MSR',1664);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Morocco',N'المغرب','MA','MAR',212);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Mozambique',N'موزمبيق','MZ','MOZ',258);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Myanmar',N'ميانمار','MM','MMR',95);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Namibia',N'ناميبيا','NA','NAM',264);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Nauru',N'ناورو','NR','NRU',674);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Nepal',N'نيبال','NP','NPL',977);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Netherlands',N'هولندا','NL','NLD',31);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Netherlands Antilles',N'جزر الأنتيل الهولندية','AN','ANT',599);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('New Caledonia',N'كاليدونيا الجديدة','NC','NCL',687);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('New Zealand',N'نيوزيلندا','NZ','NZL',64);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Nicaragua',N'نيكاراغوا','NI','NIC',505);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Niger',N'النيجر','NE','NER',227);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Nigeria',N'نيجيريا','NG','NGA',234);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Niue',N'نييوي','NU','NIU',683);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Norfolk Island',N'جزيرة نورفولك','NF','NFK',6723);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('North Korea',N'كوريا الشمالية','KP','PRK',850);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('North Macedonia',N'مقدونيا الشمالية','MK','MKD',389);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Northern Mariana Islands',N'جزر ماريانا الشمالية','MP','MNP',1);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Norway',N'النرويج','NO','NOR',47);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Oman',N'سلطنة عمان','OM','OMN',968);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Pakistan',N'باكستان','PK','PAK',92);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Palau',N'بالاو','PW','PLW',680);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Palestine',N'فلسطين','PS','PSE',970);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Panama',N'بنما','PA','PAN',507);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Papua New Guinea',N'بابوا غينيا الجديدة','PG','PNG',675);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Paraguay',N'باراغواي','PY','PRY',595);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Peru',N'بيرو','PE','PER',51);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Philippines',N'الفلبين','PH','PHL',63);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Pitcairn Islands',N'جزر بيتكيرن','PN','PCN',672);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Poland',N'بولندا','PL','POL',48);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Portugal',N'البرتغال','PT','PRT',351);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Puerto Rico',N'بورتوريكو','PR','PRI',1787);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Qatar',N'قطر','QA','QAT',974);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Réunion',N'ريونيون','RE','REU',262);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Romania',N'رومانيا','RO','ROU',40);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Russia',N'روسيا','RU','RUS',7);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Rwanda',N'رواندا','RW','RWA',250);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Saint Barthélemy',N'سان بارتيلمي','BL','BLM',590);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Saint Helena',N'سانت هيلينا','SH','SHN',290);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Saint Kitts and Nevis',N'سانت كيتس ونيفيس','KN','KNA',1869);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Saint Lucia',N'سانت لوسيا','LC','LCA',1758);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Saint Martin',N'سانت مارتن','MF','MAF',590);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Saint Pierre and Miquelon',N'سان بيير وميكلون','PM','SPM',508);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Saint Vincent and the Grenadines',N'سانت فينسنت والغرينادين','VC','VCT',784);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Samoa',N'ساموا','WS','WSM',685);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('San Marino',N'سان مارينو','SM','SMR',378);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('São Tomé and Príncipe',N'ساو تومي وبرينسيب','ST','STP',239);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Saudi Arabia',N'السعودية','SA','SAU',966);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Senegal',N'السنغال','SN','SEN',221);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Serbia',N'صربيا','RS','SRB',381);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Seychelles',N'سيشل','SC','SYC',248);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Sierra Leone',N'سيراليون','SL','SLE',232);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Singapore',N'سنغافورة','SG','SGP',65);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Sint Maarten',N'سانت مارتن','SX','SXM',599);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Slovakia',N'سلوفاكيا','SK','SVK',421);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Slovenia',N'سلوفينيا','SI','SVN',386);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Solomon Islands',N'جزر سليمان','SB','SLB',677);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Somalia',N'الصومال','SO','SOM',252);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('South Africa',N'جنوب أفريقيا','ZA','ZAF',27);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('South Georgia and South Sandwich Islands',N'جورجيا الجنوبية وجزر ساندويتش الجنوبية','GS','SGS',500);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('South Korea',N'كوريا الجنوبية','KR','KOR',82);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('South Sudan',N'جنوب السودان','SS','SSD',211);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Spain',N'إسبانيا','ES','ESP',34);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Sri Lanka',N'سريلانكا','LK','LKA',94);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Sudan',N'السودان','SD','SDN',249);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Suriname',N'سورينام','SR','SUR',597);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Svalbard and Jan Mayen',N'سفالبارد ويان ماين','SJ','SJM',47);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Sweden',N'السويد','SE','SWE',46);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Switzerland',N'سويسرا','CH','CHE',41);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Syria',N'سوريا','SY','SYR',963);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Taiwan',N'تايوان','TW','TWN',886);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Tajikistan',N'طاجيكستان','TJ','TJK',992);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Tanzania',N'تنزانيا','TZ','TZA',255);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Thailand',N'تايلاند','TH','THA',66);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Timor_Leste',N'تيمور الشرقية','TL','TLS',670);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Togo',N'توجو','TG','TGO',228);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Tokelau',N'توكيلاو','TK','TKL',690);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Tonga',N'تونغا','TO','TON',676);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Trinidad and Tobago',N'ترينيداد وتوباغو','TT','TTO',868);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Tunisia',N'تونس','TN','TUN',216);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Turkey',N'تركيا','TR','TUR',90);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Turkmenistan',N'تركمانستان','TM','TKM',993);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Turks and Caicos Islands',N'جزر توركس وكايكوس','TC','TCA',1);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Tuvalu',N'توفالو','TV','TUV',688);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('U.S. Minor Outlying Islands',N'جزر الولايات المتحدة الصغيرة النائية','UM','UMI',246);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('U.S. Virgin Islands',N'جزر العذراء الأمريكية','VI','VIR',1);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Uganda',N'أوغندا','UG','UGA',256);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Ukraine',N'أوكرانيا','UA','UKR',380);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('United Arab Emirates',N'الإمارات العربية المتحدة','AE','ARE',971);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('United Kingdom',N'المملكة المتحدة','GB','GBR',44);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('United States of America',N'الولايات المتحدة الأمريكية','US','USA',1);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Uruguay',N'أوروغواي','UY','URY',598);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Uzbekistan',N'أوزبكستان','UZ','UZB',998);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Vanuatu',N'فانواتو','VU','VUT',678);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Vatican City',N'مدينة الفاتيكان','VA','VAT',379);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Venezuela',N'فنزويلا','VE','VEN',58);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Vietnam',N'فيتنام','VN','VNM',84);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Wallis and Futuna',N'واليس وفوتونا','WF','WLF',681);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Western Sahara',N'الصحراء الغربية','EH','ESH',212);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Yemen',N'اليمن','YE','YEM',967);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Zambia',N'زامبيا','ZM','ZMB',260);
                INSERT INTO Countries(ENGLISHNAME,ArabicName,Alpha2Code,Alpha3Code,PhoneCode) VALUES ('Zimbabwe',N'زيمبابوي','ZW','ZWE',263);

                ");
            #endregion

            #region  Languages

            builder.Sql(@"
                INSERT INTO Languages(code,name,nativeName) VALUES ('ab','Abkhaz',N'аҧсуа');
                INSERT INTO Languages(code,name,nativeName) VALUES ('aa','Afar',N'Afaraf');
                INSERT INTO Languages(code,name,nativeName) VALUES ('af','Afrikaans',N'Afrikaans');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ak','Akan',N'Akan');
                INSERT INTO Languages(code,name,nativeName) VALUES ('sq','Albanian',N'Shqip');
                INSERT INTO Languages(code,name,nativeName) VALUES ('am','Amharic',N'አማርኛ');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ar','Arabic',N'العربية');
                INSERT INTO Languages(code,name,nativeName) VALUES ('an','Aragonese',N'Aragonés');
                INSERT INTO Languages(code,name,nativeName) VALUES ('hy','Armenian',N'Հայերեն');
                INSERT INTO Languages(code,name,nativeName) VALUES ('as','Assamese',N'অসমীয়া');
                INSERT INTO Languages(code,name,nativeName) VALUES ('av','Avaric',N'авар мацӀ, магӀарул мацӀ');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ae','Avestan',N'avesta');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ay','Aymara',N'aymar aru');
                INSERT INTO Languages(code,name,nativeName) VALUES ('az','Azerbaijani',N'azərbaycan dili');
                INSERT INTO Languages(code,name,nativeName) VALUES ('bm','Bambara',N'bamanankan');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ba','Bashkir',N'башҡорт теле');
                INSERT INTO Languages(code,name,nativeName) VALUES ('eu','Basque',N'euskara, euskera');
                INSERT INTO Languages(code,name,nativeName) VALUES ('be','Belarusian',N'Беларуская');
                INSERT INTO Languages(code,name,nativeName) VALUES ('bn','Bengali',N'বাংলা');
                INSERT INTO Languages(code,name,nativeName) VALUES ('bh','Bihari',N'भोजपुरी');
                INSERT INTO Languages(code,name,nativeName) VALUES ('bi','Bislama',N'Bislama');
                INSERT INTO Languages(code,name,nativeName) VALUES ('bs','Bosnian',N'bosanski jezik');
                INSERT INTO Languages(code,name,nativeName) VALUES ('br','Breton',N'brezhoneg');
                INSERT INTO Languages(code,name,nativeName) VALUES ('bg','Bulgarian',N'български език');
                INSERT INTO Languages(code,name,nativeName) VALUES ('my','Burmese',N'ဗမာစာ');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ca','Catalan; Valencian',N'Català');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ch','Chamorro',N'Chamoru');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ce','Chechen',N'нохчийн мотт');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ny','Chichewa; Chewa; Nyanja',N'chiCheŵa, chinyanja');
                INSERT INTO Languages(code,name,nativeName) VALUES ('zh','Chinese',N'中文 (Zhōngwén), 汉语, 漢語');
                INSERT INTO Languages(code,name,nativeName) VALUES ('cv','Chuvash',N'чӑваш чӗлхи');
                INSERT INTO Languages(code,name,nativeName) VALUES ('kw','Cornish',N'Kernewek');
                INSERT INTO Languages(code,name,nativeName) VALUES ('co','Corsican',N'corsu, lingua corsa');
                INSERT INTO Languages(code,name,nativeName) VALUES ('cr','Cree',N'ᓀᐦᐃᔭᐍᐏᐣ');
                INSERT INTO Languages(code,name,nativeName) VALUES ('hr','Croatian',N'hrvatski');
                INSERT INTO Languages(code,name,nativeName) VALUES ('cs','Czech',N'česky, čeština');
                INSERT INTO Languages(code,name,nativeName) VALUES ('da','Danish',N'dansk');
                INSERT INTO Languages(code,name,nativeName) VALUES ('dv','Divehi; Dhivehi; Maldivian;',N'ދިވެހި');
                INSERT INTO Languages(code,name,nativeName) VALUES ('nl','Dutch',N'Nederlands, Vlaams');
                INSERT INTO Languages(code,name,nativeName) VALUES ('en','English',N'English');
                INSERT INTO Languages(code,name,nativeName) VALUES ('eo','Esperanto',N'Esperanto');
                INSERT INTO Languages(code,name,nativeName) VALUES ('et','Estonian',N'eesti, eesti keel');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ee','Ewe',N'Eʋegbe');
                INSERT INTO Languages(code,name,nativeName) VALUES ('fo','Faroese',N'føroyskt');
                INSERT INTO Languages(code,name,nativeName) VALUES ('fj','Fijian',N'vosa Vakaviti');
                INSERT INTO Languages(code,name,nativeName) VALUES ('fi','Finnish',N'suomi, suomen kieli');
                INSERT INTO Languages(code,name,nativeName) VALUES ('fr','French',N'français, langue française');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ff','Fula; Fulah; Pulaar; Pular',N'Fulfulde, Pulaar, Pular');
                INSERT INTO Languages(code,name,nativeName) VALUES ('gl','Galician',N'Galego');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ka','Georgian',N'ქართული');
                INSERT INTO Languages(code,name,nativeName) VALUES ('de','German',N'Deutsch');
                INSERT INTO Languages(code,name,nativeName) VALUES ('el','Greek, Modern',N'Ελληνικά');
                INSERT INTO Languages(code,name,nativeName) VALUES ('gn','Guaraní',N'Avañeẽ');
                INSERT INTO Languages(code,name,nativeName) VALUES ('gu','Gujarati',N'ગુજરાતી');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ht','Haitian; Haitian Creole',N'Kreyòl ayisyen');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ha','Hausa',N'Hausa, هَوُسَ');
                INSERT INTO Languages(code,name,nativeName) VALUES ('he','Hebrew (modern)',N'עברית');
                INSERT INTO Languages(code,name,nativeName) VALUES ('hz','Herero',N'Otjiherero');
                INSERT INTO Languages(code,name,nativeName) VALUES ('hi','Hindi',N'हिन्दी, हिंदी');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ho','Hiri Motu',N'Hiri Motu');
                INSERT INTO Languages(code,name,nativeName) VALUES ('hu','Hungarian',N'Magyar');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ia','Interlingua',N'Interlingua');
                INSERT INTO Languages(code,name,nativeName) VALUES ('id','Indonesian',N'Bahasa Indonesia');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ie','Interlingue',N'Originally called Occidental; then Interlingue after WWII');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ga','Irish',N'Gaeilge');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ig','Igbo',N'Asụsụ Igbo');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ik','Inupiaq',N'Iñupiaq, Iñupiatun');
                INSERT INTO Languages(code,name,nativeName) VALUES ('io','Ido',N'Ido');
                INSERT INTO Languages(code,name,nativeName) VALUES ('is','Icelandic',N'Íslenska');
                INSERT INTO Languages(code,name,nativeName) VALUES ('it','Italian',N'Italiano');
                INSERT INTO Languages(code,name,nativeName) VALUES ('iu','Inuktitut',N'ᐃᓄᒃᑎᑐᑦ');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ja','Japanese',N'日本語 (にほんご／にっぽんご)');
                INSERT INTO Languages(code,name,nativeName) VALUES ('jv','Javanese',N'basa Jawa');
                INSERT INTO Languages(code,name,nativeName) VALUES ('kl','Kalaallisut, Greenlandic',N'kalaallisut, kalaallit oqaasii');
                INSERT INTO Languages(code,name,nativeName) VALUES ('kn','Kannada',N'ಕನ್ನಡ');
                INSERT INTO Languages(code,name,nativeName) VALUES ('kr','Kanuri',N'Kanuri');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ks','Kashmiri',N'कश्मीरी, كشميري‎');
                INSERT INTO Languages(code,name,nativeName) VALUES ('kk','Kazakh',N'Қазақ тілі');
                INSERT INTO Languages(code,name,nativeName) VALUES ('km','Khmer',N'ភាសាខ្មែរ');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ki','Kikuyu, Gikuyu',N'Gĩkũyũ');
                INSERT INTO Languages(code,name,nativeName) VALUES ('rw','Kinyarwanda',N'Ikinyarwanda');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ky','Kirghiz, Kyrgyz',N'кыргыз тили');
                INSERT INTO Languages(code,name,nativeName) VALUES ('kv','Komi',N'коми кыв');
                INSERT INTO Languages(code,name,nativeName) VALUES ('kg','Kongo',N'KiKongo');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ko','Korean',N'한국어 (韓國語), 조선말 (朝鮮語)');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ku','Kurdish',N'Kurdî, كوردی‎');
                INSERT INTO Languages(code,name,nativeName) VALUES ('kj','Kwanyama, Kuanyama',N'Kuanyama');
                INSERT INTO Languages(code,name,nativeName) VALUES ('la','Latin',N'latine, lingua latina');
                INSERT INTO Languages(code,name,nativeName) VALUES ('lb','Luxembourgish, Letzeburgesch',N'Lëtzebuergesch');
                INSERT INTO Languages(code,name,nativeName) VALUES ('lg','Luganda',N'Luganda');
                INSERT INTO Languages(code,name,nativeName) VALUES ('li','Limburgish, Limburgan, Limburger',N'Limburgs');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ln','Lingala',N'Lingála');
                INSERT INTO Languages(code,name,nativeName) VALUES ('lo','Lao',N'ພາສາລາວ');
                INSERT INTO Languages(code,name,nativeName) VALUES ('lt','Lithuanian',N'lietuvių kalba');
                INSERT INTO Languages(code,name,nativeName) VALUES ('lu','Luba_Katanga','Luba_Katanga');
                INSERT INTO Languages(code,name,nativeName) VALUES ('lv','Latvian',N'latviešu valoda');
                INSERT INTO Languages(code,name,nativeName) VALUES ('gv','Manx',N'Gaelg, Gailck');
                INSERT INTO Languages(code,name,nativeName) VALUES ('mk','Macedonian',N'македонски јазик');
                INSERT INTO Languages(code,name,nativeName) VALUES ('mg','Malagasy',N'Malagasy fiteny');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ms','Malay',N'bahasa Melayu, بهاس ملايو‎');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ml','Malayalam',N'മലയാളം');
                INSERT INTO Languages(code,name,nativeName) VALUES ('mt','Maltese',N'Malti');
                INSERT INTO Languages(code,name,nativeName) VALUES ('mi','Māori',N'te reo Māori');
                INSERT INTO Languages(code,name,nativeName) VALUES ('mr','Marathi (Marāṭhī)',N'मराठी');
                INSERT INTO Languages(code,name,nativeName) VALUES ('mh','Marshallese',N'Kajin M̧ajeļ');
                INSERT INTO Languages(code,name,nativeName) VALUES ('mn','Mongolian',N'монгол');
                INSERT INTO Languages(code,name,nativeName) VALUES ('na','Nauru',N'Ekakairũ Naoero');
                INSERT INTO Languages(code,name,nativeName) VALUES ('nv','Navajo, Navaho',N'Diné bizaad, Dinékʼehǰí');
                INSERT INTO Languages(code,name,nativeName) VALUES ('nb','Norwegian Bokmål',N'Norsk bokmål');
                INSERT INTO Languages(code,name,nativeName) VALUES ('nd','North Ndebele',N'isiNdebele');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ne','Nepali',N'नेपाली');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ng','Ndonga',N'Owambo');
                INSERT INTO Languages(code,name,nativeName) VALUES ('nn','Norwegian Nynorsk',N'Norsk nynorsk');
                INSERT INTO Languages(code,name,nativeName) VALUES ('no','Norwegian',N'Norsk');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ii','Nuosu',N'ꆈꌠ꒿ Nuosuhxop');
                INSERT INTO Languages(code,name,nativeName) VALUES ('nr','South Ndebele',N'isiNdebele');
                INSERT INTO Languages(code,name,nativeName) VALUES ('oc','Occitan',N'Occitan');
                INSERT INTO Languages(code,name,nativeName) VALUES ('oj','Ojibwe, Ojibwa',N'ᐊᓂᔑᓈᐯᒧᐎᓐ');
                INSERT INTO Languages(code,name,nativeName) VALUES ('cu','Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic',N'ѩзыкъ словѣньскъ');
                INSERT INTO Languages(code,name,nativeName) VALUES ('om','Oromo',N'Afaan Oromoo');
                INSERT INTO Languages(code,name,nativeName) VALUES ('or','Oriya',N'ଓଡ଼ିଆ');
                INSERT INTO Languages(code,name,nativeName) VALUES ('os','Ossetian, Ossetic',N'ирон æвзаг');
                INSERT INTO Languages(code,name,nativeName) VALUES ('pa','Panjabi, Punjabi',N'ਪੰਜਾਬੀ, پنجابی‎');
                INSERT INTO Languages(code,name,nativeName) VALUES ('pi','Pāli',N'पाऴि');
                INSERT INTO Languages(code,name,nativeName) VALUES ('fa','Persian',N'فارسی');
                INSERT INTO Languages(code,name,nativeName) VALUES ('pl','Polish',N'polski');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ps','Pashto, Pushto',N'پښتو');
                INSERT INTO Languages(code,name,nativeName) VALUES ('pt','Portuguese',N'Português');
                INSERT INTO Languages(code,name,nativeName) VALUES ('qu','Quechua',N'Runa Simi, Kichwa');
                INSERT INTO Languages(code,name,nativeName) VALUES ('rm','Romansh',N'rumantsch grischun');
                INSERT INTO Languages(code,name,nativeName) VALUES ('rn','Kirundi',N'kiRundi');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ro','Romanian, Moldavian, Moldovan',N'română');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ru','Russian',N'русский язык');
                INSERT INTO Languages(code,name,nativeName) VALUES ('sa','Sanskrit (Saṁskṛta)',N'संस्कृतम्');
                INSERT INTO Languages(code,name,nativeName) VALUES ('sc','Sardinian',N'sardu');
                INSERT INTO Languages(code,name,nativeName) VALUES ('sd','Sindhi',N'सिन्धी, سنڌي، سندھی‎');
                INSERT INTO Languages(code,name,nativeName) VALUES ('se','Northern Sami',N'Davvisámegiella');
                INSERT INTO Languages(code,name,nativeName) VALUES ('sm','Samoan',N'gagana faa Samoa');
                INSERT INTO Languages(code,name,nativeName) VALUES ('sg','Sango',N'yângâ tî sängö');
                INSERT INTO Languages(code,name,nativeName) VALUES ('sr','Serbian',N'српски језик');
                INSERT INTO Languages(code,name,nativeName) VALUES ('gd','Scottish Gaelic; Gaelic',N'Gàidhlig');
                INSERT INTO Languages(code,name,nativeName) VALUES ('sn','Shona',N'chiShona');
                INSERT INTO Languages(code,name,nativeName) VALUES ('si','Sinhala, Sinhalese',N'සිංහල');
                INSERT INTO Languages(code,name,nativeName) VALUES ('sk','Slovak',N'slovenčina');
                INSERT INTO Languages(code,name,nativeName) VALUES ('sl','Slovene',N'slovenščina');
                INSERT INTO Languages(code,name,nativeName) VALUES ('so','Somali',N'Soomaaliga, af Soomaali');
                INSERT INTO Languages(code,name,nativeName) VALUES ('st','Southern Sotho',N'Sesotho');
                INSERT INTO Languages(code,name,nativeName) VALUES ('es','Spanish; Castilian',N'español, castellano');
                INSERT INTO Languages(code,name,nativeName) VALUES ('su','Sundanese',N'Basa Sunda');
                INSERT INTO Languages(code,name,nativeName) VALUES ('sw','Swahili',N'Kiswahili');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ss','Swati',N'SiSwati');
                INSERT INTO Languages(code,name,nativeName) VALUES ('sv','Swedish',N'svenska');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ta','Tamil',N'தமிழ்');
                INSERT INTO Languages(code,name,nativeName) VALUES ('te','Telugu',N'తెలుగు');
                INSERT INTO Languages(code,name,nativeName) VALUES ('tg','Tajik',N'тоҷикӣ, toğikī, تاجیکی‎');
                INSERT INTO Languages(code,name,nativeName) VALUES ('th','Thai',N'ไทย');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ti','Tigrinya',N'ትግርኛ');
                INSERT INTO Languages(code,name,nativeName) VALUES ('bo','Tibetan Standard, Tibetan, Central',N'བོད་ཡིག');
                INSERT INTO Languages(code,name,nativeName) VALUES ('tk','Turkmen',N'Türkmen, Түркмен');
                INSERT INTO Languages(code,name,nativeName) VALUES ('tl','Tagalog',N'Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔');
                INSERT INTO Languages(code,name,nativeName) VALUES ('tn','Tswana',N'Setswana');
                INSERT INTO Languages(code,name,nativeName) VALUES ('to','Tonga (Tonga Islands)',N'faka Tonga');
                INSERT INTO Languages(code,name,nativeName) VALUES ('tr','Turkish',N'Türkçe');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ts','Tsonga',N'Xitsonga');
                INSERT INTO Languages(code,name,nativeName) VALUES ('tt','Tatar',N'татарча, tatarça, تاتارچا‎');
                INSERT INTO Languages(code,name,nativeName) VALUES ('tw','Twi',N'Twi');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ty','Tahitian',N'Reo Tahiti');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ug','Uighur, Uyghur',N'Uyƣurqə, ئۇيغۇرچە‎');
                INSERT INTO Languages(code,name,nativeName) VALUES ('uk','Ukrainian',N'українська');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ur','Urdu',N'اردو');
                INSERT INTO Languages(code,name,nativeName) VALUES ('uz','Uzbek',N'zbek, Ўзбек, أۇزبېك‎');
                INSERT INTO Languages(code,name,nativeName) VALUES ('ve','Venda',N'Tshivenḓa');
                INSERT INTO Languages(code,name,nativeName) VALUES ('vi','Vietnamese',N'Tiếng Việt');
                INSERT INTO Languages(code,name,nativeName) VALUES ('vo','Volapük',N'Volapük');
                INSERT INTO Languages(code,name,nativeName) VALUES ('wa','Walloon',N'Walon');
                INSERT INTO Languages(code,name,nativeName) VALUES ('cy','Welsh',N'Cymraeg');
                INSERT INTO Languages(code,name,nativeName) VALUES ('wo','Wolof',N'Wollof');
                INSERT INTO Languages(code,name,nativeName) VALUES ('fy','Western Frisian',N'Frysk');
                INSERT INTO Languages(code,name,nativeName) VALUES ('xh','Xhosa',N'isiXhosa');
                INSERT INTO Languages(code,name,nativeName) VALUES ('yi','Yiddish',N'ייִדיש');
                INSERT INTO Languages(code,name,nativeName) VALUES ('yo','Yoruba',N'Yorùbá');
                INSERT INTO Languages(code,name,nativeName) VALUES ('za','Zhuang, Chuang',N'Saɯ cueŋƅ, Saw cuengh');

");

            #endregion
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
